### ISSUE TITLE
ILGPU.Algorithms 0.7.1 is not available on NuGet

### ISSUE THREAD

**Issue by BenjaminPelletier** [m4rs-mt/ILGPU.Samples#8]
When the solution in master (ebc656) is loaded, Visual Studio gives the error:

```
NU1102	Unable to find package ILGPU.Algorithms with version (>= 0.7.1)
  - Found 1 version(s) in nuget.org [ Nearest version: 0.7.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
AlgorithmsCuBlas
C:\Code\m4rs-mt\ILGPU.Samples\Src\AlgorithmsCuBlas\AlgorithmsCuBlas.csproj
```

This is because 0.7.1 for ILGPU.Algorithms is not available on NuGet; 0.7.0 is the newest available version.

**Comment by m4rs-mt** [comment]
@BenjaminPelletier Yes, that is true. I already prepared a sample for the upcoming version of the algorithms library. It will take some additional days until the new algorithms package will be available.
